### ISSUE TITLE
MultiFactorAuthentication failed, must provide both MFA serial number and one time pass code

### ISSUE THREAD

**Issue by yupyvovarov** [adenot/hiera-eyaml-kms#13]
Dear,
I have AWS role with MFA which is responsible for KMS encrypt. I am assuming the role in command and able to encrypt with `aws kms encrypt` command. But when I am using `eyaml encrypt` I've got the error: 
`
[hiera-eyaml-core] MultiFactorAuthentication failed, must provide both MFA serial number and one time pass code.
`

```bash
$ eyaml --version
Welcome to eyaml 3.2.0

Usage:
eyaml subcommand [global-opts] [subcommand-opts]

Available subcommands:
        encrypt: encrypt some data
     createkeys: create a set of keys with which to encrypt/decrypt eyaml data
        decrypt: decrypt some data
        version: show version information
        recrypt: recrypt an eyaml file
           edit: edit an eyaml file

For more help on an individual command, use --help on that command

Installed Plugins:
	kms
```

Please help, how to fix this?

**Comment by neilwelling** [comment]
Hi - did you ever get a resolution for this, or a workaround? I'm having the same issues and I've tried adding a session token into my credentials file instead but I get 

`[hiera-eyaml-core] The security token included in the request is invalid`

**Comment by neilwelling** [comment]
I was being an idiot. I didn't set the temp access and secret keys in my credentials file, just the token, so it was using keys against a different profile. All working now
