### ISSUE TITLE
AWS Profile addition

### ISSUE THREAD

**Issue by varspare** [adenot/hiera-eyaml-kms#3]
[added-kms-aws-profile-option.patch.txt](https://github.com/adenot/hiera-eyaml-kms/files/1295521/added-kms-aws-profile-option.patch.txt)

Patch to add the option to change the AWS profile in the command - handy when working with multiple accounts.

**Comment by adenot** [comment]
@varspare Would you mind doing a pull request with your patch?

**Comment by varspare** [comment]
sure

**Comment by varspare** [comment]
created PR https://github.com/adenot/hiera-eyaml-kms/pull/4
