### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by joshuaspence** [adenot/hiera-eyaml-kms#5]
[`hiera-eyaml-kms` on RubyGems](https://rubygems.org/gems/hiera-eyaml-kms) hasn't been updated since August 2015. Is there any chance of publishing a new version of this gem to RubyGems?

**Comment by adenot** [comment]
Hi Joshua, thanks for the heads up, I will make a release in the following days.

**Comment by JohnPeacockMessageSystems** [comment]
PING  You still haven't released this AFAICT

**Comment by Zordrak** [comment]
Major ping on this from me too. 
0.1 requires that we install the entire aws-sdk on every docker build, but per changes 8 months ago, we only really need aws-sdk-kms. The change is in place, we'd *love* to see 0.2 published to rubygems.

**Comment by adenot** [comment]
Apologies for the delay, version 0.2 is now published.
