### ISSUE TITLE
Cannot encrypt strings larger than 4096 chars

### ISSUE THREAD

**Issue by retizu** [adenot/hiera-eyaml-kms#8]
When trying to encrypt a string > 4096 chars long the engine returns the error : 

`[hiera-eyaml-core] 1 validation error detected: Value at 'plaintext' failed to satisfy constraint: Member must have length less than or equal to 4096`

The restriction is likely from [AWS KMS](http://docs.aws.amazon.com/kms/latest/APIReference/API_Encrypt.html) 

"You can encrypt up to 4 kilobytes (4096 bytes) of arbitrary data such as an RSA key, a database password, or other sensitive information. "

**Comment by adenot** [comment]
Yes, unfortunately this is a KMS limitation

**Comment by Mohitp98** [comment]
Any update/workaround to encrypt data of more than 4096 chars?
